services:
  backend:
    image: polaltes0403/backend_g1:latest
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
    networks:
      - "backend_network"
      - "frontend_network"
    restart:
      unless-stopped
    environment:
      - MONGO_URI=mongodb://mongodb:27017/ProyectoEA_bd
  mongodb:
    image: polaltes0403/custom_mongo_g1:latest
    ports:
      - "27017:27017"
    networks:
      - "backend_network"
    volumes:
      - mongo_data:/data/db
    restart:
      unless-stopped

networks:
  backend_network:
  frontend_network:  

volumes:
  mongo_data: